version: "3.8"

services:
  db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: password
    healthcheck:
      test: >
        bash -c "
        echo 'SELECT 1 FROM DUAL;' | 
        sqlplus -s sys/password@localhost:1521/XEPDB1 as sysdba |
        grep -q '1'"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
